{!! Html::style(asset('assets/css/dataTables.bootstrap.min.css')) !!}
{!! Html::style(asset('assets/css/bootstrap.min.css')) !!}
{!! Html::style(asset('assets/css/font-awesome.min.css')) !!}
{!! Html::style(asset('assets/css/theme.min.css')) !!}
{!! Html::style(asset('assets/css/theme-skin.min.css')) !!}
{!! Html::style(asset('assets/css/pace.css')) !!}
{!! Html::style(asset('assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')) !!}
{!! Html::style(asset('assets/plugins/pikaday/pikaday.css')) !!}
{!! Html::style(asset('assets/plugins/chosen/chosen.css')) !!}
{!! Html::style(asset('assets/plugins/animsition/css/animsition.min.css')) !!}
{!! Html::style(asset('assets/plugins/amaranjs//css/amaran.min.css')) !!}
{!! Html::style(asset('assets/css/style.css')) !!}